In [77]:
import pandas as pd

# Specify the filename
filename = 'train.csv'

# Read the CSV file into a DataFrame
data = pd.read_csv(filename)

In [78]:
data.head()
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230130 entries, 0 to 230129
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        230130 non-null  int64
 1   date      230130 non-null  object
 2   country   230130 non-null  object
 3   store     230130 non-null  object
 4   product   230130 non-null  object
 5   num_sold  221259 non-null  float64
dtypes: float64(1), int64(1), object(4)
memory usage: 10.5+ MB

In [54]:
unique_countries = data['country'].nunique()
print(f"Number of unique countries: {unique_countries}")

# Count the number of entries for each country
country_counts = data['country'].value_counts()

# Display the counts for each country
print("\nNumber of entries for each country:")
print(country_counts)

Number of unique countries: 6

Number of entries for each country:
country
Canada       38355
Finland      38355
Italy        38355
Kenya        38355
Norway       38355
Singapore    38355
Name: count, dtype: int64

In [55]:
null_counts = data.isnull().sum()
print(null_counts)

id             0
date           0
country        0
store          0
product        0
num_sold    8871
dtype: int64

In [56]:
null_num_sold_df = data[data['num_sold'].isnull()]

In [57]:
data = data[data['num_sold'].notnull()]

In [58]:
unique_countries = data['country'].nunique()
print(f"Number of unique countries: {unique_countries}")

# Count the number of entries for each country
country_counts = data['country'].value_counts()

# Display the counts for each country
print("\nNumber of entries for each country:")
print(country_counts)

Number of unique countries: 6

Number of entries for each country:
country
Finland      38355
Italy        38355
Norway       38355
Singapore    38355
Canada       34109
Kenya        33730
Name: count, dtype: int64

In [59]:
unique_countries_null = null_num_sold_df['country'].nunique()
print(f"Number of unique countries: {unique_countries_null}")

# Count the number of entries for each country
country_counts = null_num_sold_df['country'].value_counts()

# Display the counts for each country
print("\nNumber of entries for each country:")
print(country_counts)

Number of unique countries: 2

Number of entries for each country:
country
Kenya     4625
Canada    4246
Name: count, dtype: int64

In [60]:
# Identify duplicates in the 'i' column
duplicates = data[data.duplicated(subset='id', keep=False)]

# Display the rows with duplicates in the 'i' column
print("Rows with duplicate entries in the 'id' column:")
duplicates

Rows with duplicate entries in the 'id' column:

Empty DataFrame
Columns: [id, date, country, store, product, num_sold]
Index: []

In [61]:
# Identify duplicates in the 'i' column
duplicates = null_num_sold_df[null_num_sold_df.duplicated(subset='id', keep=False)]

# Display the rows with duplicates in the 'i' column
print("Rows with duplicate entries in the 'id' column:")
duplicates

Rows with duplicate entries in the 'id' column:

Empty DataFrame
Columns: [id, date, country, store, product, num_sold]
Index: []

In [62]:
unique_product = data['product'].nunique()
print(f"Number of unique product: {unique_countries}")

# Count the number of entries for each country
product_counts = data['product'].value_counts()

# Display the counts for each country
print("\nNumber of entries for each product:")
print(product_counts)

Number of unique product: 6

Number of entries for each product:
product
Kaggle                46026
Kaggle Tiers          46026
Kerneler Dark Mode    46025
Kerneler              45962
Holographic Goose     37220
Name: count, dtype: int64

In [68]:
unique_product_null = null_num_sold_df['product'].nunique()
print(f"Number of unique product in null: {unique_product_null}")

# Count the number of entries for each product in null category
product_counts_null = null_num_sold_df['product'].value_counts()

# Display the counts for each product in null category
print("\nNumber of entries for each product in null category:")
print(product_counts_null)

Number of unique product in null: 1

Number of entries for each product in null category:
product
Holographic Goose    8806
Name: count, dtype: int64

In [70]:
#as only 65 rows had missing num values from the nan database
null_num_sold_df = null_num_sold_df[~null_num_sold_df['product'].isin(['Kerneler', 'Kerneler Dark Mode'])]

In [73]:
store_list = data['store'].nunique()
print(f"Number of unique product in not null: {store_list}")

# Count the number of entries for each store in not null category
store_list_entires = data['store'].value_counts()

# Display the counts for each product in not null
print("\nNumber of entries for each product in not null category:")
print(store_list_entires)

Number of unique product in not null: 3

Number of entries for each product in not null category:
store
Premium Sticker Mart    75684
Stickers for Less       74044
Discount Stickers       71531
Name: count, dtype: int64

In [75]:
unique_product = data['product'].nunique()
print(f"Number of unique product in null: {unique_product}")

# Count the number of entries for each product in data non null category
product_counts = data['product'].value_counts()

# Display the counts for each product in data non null category
print("\nNumber of entries for each product in not null category:")
print(product_counts)

Number of unique product in null: 5

Number of entries for each product in not null category:
product
Kaggle                46026
Kaggle Tiers          46026
Kerneler Dark Mode    46025
Kerneler              45962
Holographic Goose     37220
Name: count, dtype: int64